### PR TITLE
Overview & Install files changed.

### PR DESCRIPTION
**Pull request by Treadmule**
Changed BitBucket to Github URL in Overview and changed Installation instructions to describe using ZIP files with Deviation Uploader. Also, fixed some typos.

### CODE REVIEW

**Comment by Experienced** [comment]
Looks like I might have Pull Requests sorted out. Please tell me if anything needs fixed.

**Comment by PhracturedBlue** [comment]
It generally looks ok, but tehre is a typo (look for 'upgdating').  Also, why are you replacing 'upgrading' with 'updating'?  I'm not sure how I feel about that change.

**Comment by Experienced** [comment]
I've fixed the typo and reverted back to "upgrade" throughout. I was tentative about that in the first place, so I guess I was testing the margins. Anyway, it sounds better this way from a marketing standpoint.
Now, we'll find out if I know how to resubmit.
Thanks for the guidance.

**Comment by Treadmule** [comment]
BTW, Treadmill & Experienced  are both me. Experienced was my test user - he'll go away.

I've made the edits using the online edit tool in GitHub and the changes appear to persist, thought I don't see any way to save the changes nor re-submit for review.
Also... there's an anomaly between the appearance of the text in the edit interface versus the preview interface. I'm looking specifically at the area around the section for installation with Deviation Uploader. The numbers of the steps look ok in the editor, but the preview display is wonky. Like:
1. 2) 3. 4. ... and I can't seem to fix it. Not sure how it'll actually come out in the final result.
I'll bring it up with support and see what they say.

**Comment by PhracturedBlue** [comment]
There is nothing apparently wrong with the Github preview.  Our rst files use the 'sphynx' extensions (those are all those '.. if' lines throughout the code).  Those are not proper RST syntax, and are handled by the shynx pre-processor before the final code is rendered.  So while the github editor is useful, it will not precisely show you the final product

**Comment by Experienced** [comment]
Thanks, I'm glad to hear no problem with Github.. and the merge is done.
But, I found more minor things to fix. And maybe I'll make a stab at filling in secton 2.5 - Updating the file systm with Deviation Uploader.

**Pull request merged**
